add git for checkout

diff --git a/install-git/action.yaml b/install-git/action.yaml
--- a/install-git/action.yaml
+++ b/install-git/action.yaml
@@ -1,15 +1,15 @@
-name: Install zstd
-description: Install zstd for actions/cache support
+name: Install git
+description: Install git for actions/checkout support
 
 runs:
   using: composite
   steps:
-  - name: Install zstd if needed
+  - name: Install git if needed
     shell: bash
     run: |
-      if ! command -v zstd
+      if ! command -v git
       then
-          echo "zstd not found, attempting to install"
+          echo "git not found, attempting to install"
 
           sudo=$(command -v sudo || true)
           apt_get=$(command -v apt-get || true)
@@ -20,14 +20,14 @@ runs:
           then
               echo "Found apt-get attempting to update and install"
               ${sudo} ${apt-get} -y update
-              ${sudo} ${apt-get} install -y --no-recommends zstd
+              ${sudo} ${apt-get} install -y --no-recommends git
           elfi [[ -n "${yum}" ]]
               echo "Found yum attempting to update and install"
               ${sudo} ${yum} update -y
-              ${sudo} ${yum} install -y zstd
+              ${sudo} ${yum} install -y git
           elfi [[ -n "apk" ]]
               echo "Found apk attempting to install"
-              ${sudo} ${apk} add --no-cache zstd
+              ${sudo} ${apk} add --no-cache git
           else
               echo "no supported package manager found (apt-get, yum, apk)"
           fi
